### ISSUE TITLE
Conditional CSS styling

### ISSUE THREAD

**Issue by snewsh** [elegantthemes/divi-extension-example#6]
Hi Divi Gurus,
I have created a module which uses images. If I have two instances of the module on a page, how do I code (jsx file) so that the styles are conditional upon the size of the image. I can find the height and width of the image but only using the specific class e.g my_module_image_0 or my_module_image_0 but I need to somehow use (this.) syntax but at the moment it's beyond me.

Thanks for any help.

**Comment by lots0logs** [comment]
Hi. You can use a ref on your outermost div in `render()`. Here's some pseudo code to show what I mean:

```jsx
class YourModule extends Component {

  ...

  _doStuffToImage = () => {
    const $image = $(this.node).find('img');
    // Do stuff...
  }

  componentDidMount() {
    this._doStuffToImage();
  }

  componentDidUpdate(prevProps) {
    this._doStuffToImage();
  }

  render() {
    ...
    return (
      <div ref={n => this.node = n}>
        ...
      </div>
    );
  }
}
```

**Comment by snewsh** [comment]
Thanks @lots0logs, just getting my head around React so will work out what it does and give it a try.

**Comment by snewsh** [comment]
Thanks @lots0logs That works perfect for retrieving the image size of each image. I just need to figure out how to use this information in css as a prop.

**Comment by lots0logs** [comment]
You can apply whatever style changes you need directly in the JavaScript instead of relying on the CSS.
